/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.demo.henrys.basket;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.BDDAssertions.then;

class AppTest {
    private final App app = new App();

    @Test
    void shouldHaveACatalogue() {
        then(app.getCatalogue()).isNotNull();
    }

    @Test
    void shouldHaveNonEmptyCatalogue() {
        then(app.getCatalogue()).isNotEmpty();
    }
}
