/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package uk.co.kleindelao.demo.henrys.basket;

import static java.math.BigDecimal.ZERO;
import static java.math.RoundingMode.HALF_UP;
import static java.util.Map.entry;
import static org.apache.commons.lang3.RandomUtils.nextInt;
import static org.assertj.core.api.BDDAssertions.then;

import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

class ShoppingProcessTest {
  private final ShoppingProcess shoppingProcess = new ShoppingProcess(LocalDate.now());

  @Nested
  class CatalogueTests {
    @Test
    void shouldHaveACatalogue() {
      then(shoppingProcess.getCatalogue()).isNotNull();
    }

    @Test
    void shouldHaveNonEmptyCatalogue() {
      then(shoppingProcess.getCatalogue()).isNotEmpty();
    }

    @Test
    void shouldContainSoupBreadMilkApples() {
      then(
          shoppingProcess.getCatalogue()).anySatisfy(
                                             item -> itemMatches(item, "soup", "tin", "0.65"))
                                         .anySatisfy(
                                             item -> itemMatches(item, "bread", "loaf", "0.8"))
                                         .anySatisfy(
                                             item -> itemMatches(item, "milk", "bottle", "1.3"))
                                         .anySatisfy(
                                             item -> itemMatches(item, "apples", "single", "0.1"));
    }

    private void itemMatches(final ShoppingItem item, final String expectedName,
                             final String expectedUnit,
                             final String expectedCostValue) {
      then(item.name()).isEqualTo(expectedName);
      then(item.unit()).isEqualTo(expectedUnit);
      then(item.cost()).isEqualTo(new BigDecimal(expectedCostValue));
    }
  }

  @Nested
  class BasketTests {
    @Test
    void shouldAddItemsByIndex() {
      // Given
      final var numberOfItems = nextInt(1, 10);

      // When
      shoppingProcess.addItems(1, numberOfItems);

      // Then
      then(shoppingProcess.getBasket()
                          .getContent()).containsOnly(
          entry(new ShoppingItem("bread", "loaf", new BigDecimal("0.8")), numberOfItems));
    }
  }

  @Nested
  class Total {
    @Test
    void shouldAddUpToZeroForEmptyBasket() {
      // When
      final var total = shoppingProcess.getTotalPrice();

      // Then
      then(total).isEqualTo(ZERO.setScale(2, HALF_UP));
    }

    @Test
    void shouldAddIndividualPricesForUndiscountedItems() {
      // Given
      final var numberOfBreads = nextInt(1, 10);
      final var numberOfMilks = nextInt(1, 10);
      shoppingProcess.addItems(1, numberOfBreads);
      shoppingProcess.addItems(2, numberOfMilks);

      // When
      final var total = shoppingProcess.getTotalPrice();

      // Then
      then(total).hasScaleOf(2)
                 .isEqualTo(new BigDecimal("0.8").multiply(BigDecimal.valueOf(numberOfBreads))
                                                 .add(new BigDecimal("1.3").multiply(
                                                     BigDecimal.valueOf(numberOfMilks)))
                                                 .setScale(2, HALF_UP));
    }
  }
}
