/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.demo.henrys.basket;

import com.google.common.annotations.VisibleForTesting;

import java.util.Set;

public class App {
    private final Catalogue catalogue;

    public App() {
        catalogue = new Catalogue(Set.of());
    }

    @VisibleForTesting
    Catalogue getCatalogue() {
        return catalogue;
    }

    public static void main(String[] args) {

    }
}
