/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package uk.co.kleindelao.demo.henrys.basket;

import com.google.common.annotations.VisibleForTesting;
import java.math.BigDecimal;
import java.util.Set;

public class App {
  private final Catalogue catalogue;

  public App() {
    catalogue = new Catalogue(
        Set.of(shoppingItem("soup", "tin", "0.65"), shoppingItem("bread", "loaf", "0.8"),
            shoppingItem("milk", "bottle", "1.3"), shoppingItem("apples", "single", "0.1")));
  }

  private static ShoppingItem shoppingItem(final String name, final String unit,
                                           final String costValue) {
    return new ShoppingItem(name, unit, new BigDecimal(costValue));
  }

  @VisibleForTesting
  Catalogue getCatalogue() {
    return catalogue;
  }

  public static void main(String[] args) {

  }
}
