/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.demo.henrys.basket;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
